# Debugging & Logging
logging:
  level:
    root: INFO
    io:
      lettuce: INFO
security:
  debug:
    enabled: false

# Hikari
spring:
  datasource:
    hikari:
      pool-name: ProdHikariPool
      maximum-pool-size: 70
      minimum-idle: 16

# Scheduler
scheduler:
  sync-interval-ms : 300000           # 5분
  token-cleanup-cron : "0 0 3 * * *"  # 새벽 3시

# Swagger
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
