# Apache Tomcat
server:
  tomcat:
    threads:
      max: 80
    max-connections: 500
    accept-count: 100

# Application
app:
  semaphore:
    datasource:
      allowed-connection-size: 60

# Debugging & Logging
logging:
  level:
    root: INFO
    io:
      lettuce: INFO
security:
  debug:
    enabled: false

# Scheduler
scheduler:
  sync-interval-ms : 300000           # 5분
  token-cleanup-cron : "0 0 3 * * *"  # 새벽 3시

# Spring
spring:
  datasource:
    hikari:
      pool-name: ProdHikariPool
      maximum-pool-size: 70
      minimum-idle: 16
  jpa:
    properties:
      hibernate:
        show_sql: false

# Swagger
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
