spring:
  application:
    name: modusplant
  profiles:
    active: secrets
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: ${REDIS_SSL_ENABLED}
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_CONNECTION_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      pool-name: DevHikariPool
      maximum-pool-size: 10
      minimum-idle: 3
      idle-timeout: 60000             # 10분
      max-lifetime: 1800000           # 30분
      connection-timeout: 30000       # 30초
      auto-commit: true
  flyway:
    enabled: true
    validate-on-migrate: true
    out-of-order: false
    locations: classpath:db/migration
    encoding: UTF-8
    detect-encoding: true
    clean-disabled: false
    baseline-on-migrate: true
    baseline-version: 0.0.0
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 50
          batch_versioned_data: true
        order_inserts: true
        default_schema: ${DB_SCHEMA}

# Debugging & Logging
logging:
  level:
    root: ${LOGGING_LEVEL_ROOT}
    io:
      lettuce: ${LOGGING_LEVEL_IO_LETTUCE}
security:
  debug:
    enabled: ${SECURITY_DEBUG_ENABLED}

# KeyStore
#keystore:
#  key-store: security/cert/keystore.p12
#  key-store-password: ${KEYSTORE_PASSWORD}
#  key-store-type: PKCS12
#  key-alias: modusplant-server

# Scheduler
scheduler:
  sync-interval-ms : 300000           # 5분
  token-cleanup-cron : "0 0 3 * * *"  # 새벽 3시

# JWT
jwt:
  iss: https://app.modusplant.kr
  aud: https://www.modusplant.kr
  access_duration: 1800000      # 30분
  refresh_duration: 604800000   # 7일

# Redis
redis:
  ttl:
    view_count: 10

# Swagger
springdoc:
  api-docs:
    enabled: ${SPRINGDOC_API_DOCS_ENABLED}
  swagger-ui:
    enabled: ${SPRINGDOC_SWAGGER_UI_ENABLED}

# Wasabi
cloud:
  aws:
    region:
      static: ap-northeast-2
  wasabi:
    s3:
      endpoint: ${WASABI_ENDPOINT}
      region: ${WASABI_REGION}
      access-key: ${WASABI_ACCESS_KEY}
      secret-key: ${WASABI_SECRET_KEY}
      bucket: ${WASABI_BUCKET}