# Application
app:
  semaphore:
    datasource:
      allowed-connection-size: 7

# Debugging & Logging
logging:
  level:
    root: DEBUG
    io:
      lettuce: DEBUG
security:
  debug:
    enabled: true

# Hikari
spring:
  datasource:
    hikari:
      pool-name: DevHikariPool
      maximum-pool-size: 10
      minimum-idle: 3

# Spring
spring:
  jpa:
    properties:
      hibernate:
        show_sql: true

# MinIO
minio:
  public-endpoint: ${DEV_PUBLIC_ENDPOINT}

# Scheduler
scheduler:
  sync-interval-ms : 300000           # 5분
  token-cleanup-cron : "0 0 3 * * *"  # 새벽 3시

# Swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
