spring:
  application:
    name: modusplant
  profiles:
    active: ${SPRING_ACTIVE_PROFILE:local}
    include: secrets
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: ${REDIS_SSL_ENABLED}
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_CONNECTION_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      idle-timeout: 60000             # 10분
      max-lifetime: 1800000           # 30분
      connection-timeout: 10000       # 10초
      auto-commit: true
      validation-timeout: 10000       # 10초
  flyway:
    enabled: true
    validate-on-migrate: true
    out-of-order: false
    locations: classpath:db/migration
    encoding: UTF-8
    detect-encoding: true
    clean-disabled: false
    baseline-on-migrate: true
    baseline-version: 0.0.0
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 50
          batch_versioned_data: true
        order_inserts: true
        default_schema: ${DB_SCHEMA}
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 300MB

# KeyStore
keystore:
  key-store-password: ${KEYSTORE_PASSWORD}
  key-store-type: PKCS12
  key-alias: modusplant-server
  key-store-filename: modusplant-server-keystore.12

# JWT
jwt:
  iss: https://app.modusplant.kr
  aud: https://www.modusplant.kr
  access_duration: 1800000      # 30분
  refresh_duration: 604800000   # 7일

# Redis
redis:
  ttl:
    view_count: 10

# Wasabi
cloud:
  aws:
    region:
      static: ap-northeast-2
  wasabi:
    s3:
      endpoint: ${WASABI_ENDPOINT}
      region: ${WASABI_REGION}
      access-key: ${WASABI_ACCESS_KEY}
      secret-key: ${WASABI_SECRET_KEY}
      bucket: ${WASABI_BUCKET}

# Monitoring
management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  metrics:
    enable:
      tomcat: true
    distribution:
      percentiles:
        http.server.requests: [ 0.95, 0.99 ]

server:
  tomcat:
    mbeanregistry:
      enabled: true