# Debugging & Logging
logging:
  level:
    root: DEBUG
    io:
      lettuce: DEBUG
security:
  debug:
    enabled: true

# Scheduler
scheduler:
  sync-interval-ms : 300000           # 5분
  token-cleanup-cron : "0 0 3 * * *"  # 새벽 3시

# Spring
spring:
  jpa:
    properties:
      hibernate:
        show_sql: true

# MinIO
minio:
  public-endpoint: ${DEV_PUBLIC_ENDPOINT}

# Swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
