# Apache Tomcat
server:
  tomcat:
    threads:
      max: 15
    max-connections: 100
    accept-count: 20

# Application
app:
  semaphore:
    datasource:
      allowed-connection-size: 12

# Debugging & Logging
logging:
  level:
    root: DEBUG
    io:
      lettuce: DEBUG
security:
  debug:
    enabled: true

# MinIO
minio:
  public-endpoint: ${DEV_PUBLIC_ENDPOINT}

# Scheduler
scheduler:
  sync-interval-ms : 300000           # 5분
  token-cleanup-cron : "0 0 3 * * *"  # 새벽 3시

# Spring
spring:
  datasource:
    hikari:
      pool-name: DevHikariPool
      maximum-pool-size: 15
      minimum-idle: 5
  jpa:
    properties:
      hibernate:
        show_sql: true

# Swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
